import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Design tokens — "High-End Food Editorial" (Stitch: Bangalore Food Map)
        'tertiary-fixed': '#b9eaff',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#ffb693',
        'on-secondary-fixed': '#1c1b1b',
        error: '#ba1a1a',
        'surface-container-highest': '#e2e2e2',
        'on-primary-fixed': '#351000',
        surface: '#f9f9f8',
        'primary-fixed': '#ffdbcc',
        'secondary-fixed': '#e5e2e1',
        'surface-container-lowest': '#ffffff',
        tertiary: '#00647d',
        'outline-variant': '#dcc1b5',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636262',
        'on-primary-container': '#fffbff',
        'tertiary-fixed-dim': '#70d3f7',
        'inverse-surface': '#2f3130',
        'on-background': '#1a1c1c',
        'on-secondary-fixed-variant': '#474746',
        'on-surface-variant': '#56433a',
        'tertiary-container': '#007f9e',
        'inverse-on-surface': '#f1f1f0',
        'surface-container-high': '#e8e8e7',
        'on-surface': '#1a1c1c',
        'on-error': '#ffffff',
        'on-tertiary-container': '#fafdff',
        primary: '#99420d',
        'surface-container-low': '#f3f4f3',
        'secondary-fixed-dim': '#c8c6c5',
        'inverse-primary': '#ffb693',
        background: '#f9f9f8',
        'secondary-container': '#e2dfde',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004d61',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#9c440f',
        'on-primary-fixed-variant': '#7a3000',
        'primary-container': '#b95925',
        'surface-dim': '#dadad9',
        'surface-bright': '#f9f9f8',
        'surface-container': '#eeeeed',
        'on-tertiary': '#ffffff',
        secondary: '#5f5e5e',
        outline: '#897268',
        'on-tertiary-fixed': '#001f29',
        ink: '#1a1a1a',
      },
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        'headline-sm': ['DM Sans'],
        'headline-md': ['DM Sans'],
        'headline-md-mobile': ['DM Sans'],
        'display-lg': ['DM Sans'],
        'label-caps': ['DM Sans'],
        'body-sm': ['DM Sans'],
        'body-base': ['DM Sans'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md-mobile': ['20px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'body-base': ['14px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        unit: '4px',
        'margin-mobile': '16px',
        gutter: '16px',
        'margin-desktop': '40px',
      },
    },
  },
  plugins: [],
} satisfies Config
