import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Design tokens — "NxtSpot Food Discovery Map" (Stitch dark editorial)
        background: '#131313',
        'on-background': '#e5e2e1',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#ffb95f',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d8c3ad',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#a08e7a',
        'outline-variant': '#534434',
        primary: '#ffc174',
        'on-primary': '#472a00',
        'primary-container': '#f59e0b',
        'on-primary-container': '#613b00',
        'inverse-primary': '#855300',
        'primary-fixed': '#ffddb8',
        'primary-fixed-dim': '#ffb95f',
        'on-primary-fixed': '#2a1700',
        'on-primary-fixed-variant': '#653e00',
        secondary: '#ffb77d',
        'on-secondary': '#4d2600',
        'secondary-container': '#d97707',
        'on-secondary-container': '#432100',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'on-secondary-fixed': '#2f1500',
        'on-secondary-fixed-variant': '#6e3900',
        tertiary: '#ffbea0',
        'on-tertiary': '#561f00',
        'tertiary-container': '#f79a6c',
        'on-tertiary-container': '#72300a',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb693',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#76330d',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        ink: '#0e0e0e',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-md-mobile': ['"Playfair Display"', 'serif'],
        'display-lg': ['"Playfair Display"', 'serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-base': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        unit: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '40px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
      },
    },
  },
  plugins: [],
} satisfies Config
